name: Go UnitTests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    timeout-minutes: 3
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.1

      - name: Install dependencies
        run: go get -v ./...

      - name: Run tests
        run: go test -v ./...